### ISSUE TITLE
Check for HeadWidth instead of HeadLength

### ISSUE THREAD

**Issue by TechInterMezzo** [dpieve/Arrow.Avalonia#1]
https://github.com/dpieve/Arrow.Avalonia/blob/e327e7408a12061e2779b092521fdaba9d18c278/src/Arrow.Avalonia/Controls/Arrow.axaml.cs#L233

It should be checked if HeadWidth has a value and not HeadLength.

**Comment by dpieve** [comment]
Thank you! I fixed it. Let me know if you find more issues.
