### ISSUE TITLE
Order of Properties in XAML shouldn't matter

### ISSUE THREAD

**Issue by TechInterMezzo** [dpieve/Arrow.Avalonia#2]
The sizing of the arrow head isn't working correctly if IsProportional is set to False after HeadWidth and HeadLength in XAML. It only works if IsProportional is defined before them.

The problem seems to be that IsProportional is true by default. The head size is calculated and the properties HeadWidth and HeadLength get overwritten by the calculated values. The the bound value of IsProportional gets evaluated after the them and then it's too late.

**Comment by dpieve** [comment]
Thank you! I updated it.
